# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2017-01-22 19:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sked', '0002_auto_20161212_0027'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrgGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sked.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='OrgUsers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('org_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sked.OrgGroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='orgusers',
            unique_together=set([('org_group', 'user')]),
        ),
    ]
