# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 05:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='product_tasks',
            new_name='job_tasks',
        ),
    ]
