# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-06 05:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_auto_20160706_0512'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtaskmetrics',
            name='group',
        ),
        migrations.DeleteModel(
            name='JobTaskMetrics',
        ),
    ]
