# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0007_alter_validators_add_error_messages'),
        ('scheduler', '0002_auto_20160614_0007'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobTaskMetrics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('high', models.IntegerField()),
                ('medium', models.IntegerField()),
                ('low', models.IntegerField()),
                ('cp', models.IntegerField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='backlog_minutes_changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='completion_time',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='expertise_level',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
