# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 01:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160706_0514'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='job_tasks',
            new_name='product_tasks',
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='completion_minutes',
            field=models.IntegerField(null=True),
        ),
    ]
