# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-17 23:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_auto_20160617_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljobtask',
            name='backlog_minutes_changed',
        ),
        migrations.RemoveField(
            model_name='historicaljobtask',
            name='completion_time',
        ),
        migrations.RemoveField(
            model_name='historicaljobtask',
            name='expertise_level',
        ),
    ]
