# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-28 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160617_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaljobtask',
            name='completion_status_change',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='job_status_description',
            field=models.CharField(default='Active', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='task_expertise_description',
            field=models.CharField(default='High', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='task_minutes',
            field=models.IntegerField(default=10),
            preserve_default=False,
        ),
    ]
