# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-07-21 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0004_auto_20160721_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicaljobtask',
            name='completion_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
