# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 05:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0014_historicaljob_historicaljobtask'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusHistory',
        ),
    ]
