# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0015_delete_statushistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tasks',
            field=models.ManyToManyField(through='scheduler.ProductTask', to='scheduler.Task'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Product'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Task'),
        ),
    ]
