# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0016_auto_20160530_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljobtask',
            name='product_task',
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='product_task',
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduler.Task'),
        ),
        migrations.AddField(
            model_name='job',
            name='tasks',
            field=models.ManyToManyField(through='scheduler.JobTask', to='scheduler.Task'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='scheduler.Task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.Job'),
        ),
    ]
