# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-30 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0017_auto_20160530_0538'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaljobtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='job',
            name='tasks',
        ),
        migrations.RemoveField(
            model_name='jobtask',
            name='task',
        ),
        migrations.RemoveField(
            model_name='product',
            name='tasks',
        ),
        migrations.AddField(
            model_name='historicaljobtask',
            name='product_task',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='scheduler.ProductTask'),
        ),
        migrations.AddField(
            model_name='jobtask',
            name='product_task',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='scheduler.ProductTask'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobtask',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_tasks', to='scheduler.Job'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='scheduler.Product'),
        ),
        migrations.AlterField(
            model_name='producttask',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_tasks', to='scheduler.Task'),
        ),
    ]
